/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConPaqueteViaje;
import resources.MyIntFilter;
import dto.Servicio;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.PlainDocument;
import org.jdatepicker.JDatePanel;

/**
 *
 * @author luisponce
 */
public class PaqueteNuevoNew extends javax.swing.JPanel {
    private JTextArea descripcion;
    private JTextField origen, numPasajeros, destino;
    private JTable viajes;
    private JDatePanel fechaIda, fechaRegreso;
    private JLabel precio, fecha;
    private JComboBox transporte;
    private int precioTotal = 0;
    private ArrayList<Servicio> servicios = new ArrayList<Servicio>();
    ConPaqueteViaje controllerPaqueteViaje = new ConPaqueteViaje(); 
    /**
     * Creates new form PaqueteNuevoNew
     */
    public PaqueteNuevoNew() {
        initComponents();
        descripcion = this.txtDescripcion;
        origen = this.txtOrigenTerminal;
        
        PlainDocument doc = (PlainDocument) this.txtNumPasajeros.getDocument();
        doc.setDocumentFilter(new MyIntFilter());
        
        numPasajeros = this.txtNumPasajeros;
        destino = this.txtOrigenCiudad;
        viajes = this.listadoViajes;
        fechaIda = this.dateIda;
        fechaRegreso = this.dateRegreso;
        precio = this.lblPrecio;
        transporte = this.cbTipoTransporte;
        
        this.listadoEstadia.setEnabled(false);
        this.listadoSeguros.setEnabled(false);
        this.listadoViajes.setEnabled(false);
        this.servicios.clear();
        
//        DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
//        Date fechaHoy = new Date();
//        String fechaahora = df.format(fechaHoy);
//        precio.setText("0");
//        fecha.setText(fechaahora);
        this.fechaRegreso.setEnabled(false);
        this.btnOtraConsulta.setEnabled(false);
    }
    
    public void limpiarTablas() {
        DefaultTableModel model = (DefaultTableModel) this.listadoSeguros.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model = (DefaultTableModel) this.listadoEstadia.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model = (DefaultTableModel) this.listadoViajes.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
    }
    
    public void activarCampos(){
        this.listadoEstadia.setEnabled(false);
        this.listadoSeguros.setEnabled(false);
        this.listadoViajes.setEnabled(false);
        this.dateIda.setEnabled(true);
        this.dateRegreso.setEnabled(true);
        this.btnConsultar.setEnabled(true);
        this.cbTipoTransporte.setEnabled(true);
        this.destino.setEnabled(true);
        this.numPasajeros.setEnabled(true);
        this.origen.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtOrigenTerminal = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cbTipoTransporte = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtOrigenCiudad = new javax.swing.JTextField();
        txtNumPasajeros = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        dateIda = new org.jdatepicker.JDatePanel();
        dateRegreso = new org.jdatepicker.JDatePanel();
        btnOtraConsulta = new javax.swing.JButton();
        txtOrigenPais = new javax.swing.JTextField();
        txtDestinoTerminal = new javax.swing.JTextField();
        txtDestinoCiudad = new javax.swing.JTextField();
        txtDestinoPais = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoViajes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listadoEstadia = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listadoSeguros = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        headerPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        verPaquetesTuristicos = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(245, 245, 245));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Descripción del paquete turístico");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Valor del paquete:");

        lblPrecio.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(153, 153, 153));
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecio.setText("$ 2200500");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecio)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("1. Consultar viaje");

        jPanel8.setBackground(new java.awt.Color(245, 245, 245));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Origen");

        txtOrigenTerminal.setText("Terminal");
        txtOrigenTerminal.setToolTipText("Terminal");
        txtOrigenTerminal.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5)));
        txtOrigenTerminal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOrigenTerminalMouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Fecha de ida");

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 0, 51));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("*");

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Transporte");

        cbTipoTransporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vuelo", "Bus" }));

        jLabel40.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setText("Fecha de regreso");

        jLabel41.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 102, 102));
        jLabel41.setText("Número de Pasajeros");

        txtOrigenCiudad.setText("Ciudad");
        txtOrigenCiudad.setToolTipText("Ciudad");
        txtOrigenCiudad.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5)));
        txtOrigenCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOrigenCiudadMouseClicked(evt);
            }
        });

        txtNumPasajeros.setToolTipText("");
        txtNumPasajeros.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5)));
        txtNumPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPasajerosActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(88, 185, 87));
        btnConsultar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnConsultar.setForeground(java.awt.Color.white);
        btnConsultar.setText("Consultar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setFocusPainted(false);
        btnConsultar.setOpaque(true);
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarMouseEntered(evt);
            }
        });
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        dateIda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateIdaActionPerformed(evt);
            }
        });

        dateRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateRegresoActionPerformed(evt);
            }
        });

        btnOtraConsulta.setBackground(new java.awt.Color(153, 153, 153));
        btnOtraConsulta.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnOtraConsulta.setForeground(java.awt.Color.white);
        btnOtraConsulta.setText("Realizar otra consulta");
        btnOtraConsulta.setBorderPainted(false);
        btnOtraConsulta.setContentAreaFilled(false);
        btnOtraConsulta.setFocusPainted(false);
        btnOtraConsulta.setOpaque(true);
        btnOtraConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOtraConsultaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOtraConsultaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOtraConsultaMouseEntered(evt);
            }
        });
        btnOtraConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtraConsultaActionPerformed(evt);
            }
        });

        txtOrigenPais.setText("Pais");
        txtOrigenPais.setToolTipText("Pais");
        txtOrigenPais.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5)));
        txtOrigenPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOrigenPaisMouseClicked(evt);
            }
        });

        txtDestinoTerminal.setText("Terminal");
        txtDestinoTerminal.setToolTipText("Terminal");
        txtDestinoTerminal.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5)));
        txtDestinoTerminal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDestinoTerminalMouseClicked(evt);
            }
        });

        txtDestinoCiudad.setText("Ciudad");
        txtDestinoCiudad.setToolTipText("Ciudad");
        txtDestinoCiudad.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5)));
        txtDestinoCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDestinoCiudadMouseClicked(evt);
            }
        });

        txtDestinoPais.setText("Pais");
        txtDestinoPais.setToolTipText("Pais");
        txtDestinoPais.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5)));
        txtDestinoPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDestinoPaisMouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Destino");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOtraConsulta))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26)
                            .addComponent(txtOrigenTerminal)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDestinoTerminal)
                            .addComponent(txtNumPasajeros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrigenCiudad)
                            .addComponent(cbTipoTransporte, 0, 200, Short.MAX_VALUE)
                            .addComponent(txtDestinoCiudad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOrigenPais)
                            .addComponent(txtDestinoPais, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(dateIda, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(269, 269, 269)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addGap(47, 47, 47))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtOrigenTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtOrigenCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtOrigenPais, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtDestinoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDestinoPais, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDestinoTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel41))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(txtNumPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnOtraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cbTipoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateIda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("2. Disponibilidad");

        jPanel9.setBackground(new java.awt.Color(245, 245, 245));

        jLabel28.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Seleccione presionando con un clic dentro del listado la opción deseada.");

        listadoViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listadoViajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoViajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listadoViajes);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("3. Estadia");

        jPanel10.setBackground(new java.awt.Color(245, 245, 245));

        jLabel29.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Seleccione presionando con un clic dentro del listado la opción deseada.");

        listadoEstadia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listadoEstadia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoEstadiaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listadoEstadia);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("4. Seguros");

        jPanel11.setBackground(new java.awt.Color(245, 245, 245));

        jLabel31.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Seleccione presionando con un clic dentro del listado la opción deseada.");

        listadoSeguros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listadoSeguros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoSegurosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(listadoSeguros);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(245, 245, 245));

        btnGuardar.setBackground(new java.awt.Color(88, 185, 87));
        btnGuardar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnGuardar.setForeground(java.awt.Color.white);
        btnGuardar.setText("Crear paquete turístico");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel9.setText("Paquetes");

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("|   Nuevo");

        jLabel22.setFont(new java.awt.Font("Open Sans", 2, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("Completa los campos para crear un nuevo paquete turístico");

        verPaquetesTuristicos.setBackground(new java.awt.Color(88, 185, 87));
        verPaquetesTuristicos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        verPaquetesTuristicos.setForeground(java.awt.Color.white);
        verPaquetesTuristicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-add.png"))); // NOI18N
        verPaquetesTuristicos.setText("Ver paquetes turísticos");
        verPaquetesTuristicos.setBorderPainted(false);
        verPaquetesTuristicos.setContentAreaFilled(false);
        verPaquetesTuristicos.setFocusPainted(false);
        verPaquetesTuristicos.setOpaque(true);
        verPaquetesTuristicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verPaquetesTuristicosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verPaquetesTuristicosMouseEntered(evt);
            }
        });
        verPaquetesTuristicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPaquetesTuristicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanel1Layout = new javax.swing.GroupLayout(headerPanel1);
        headerPanel1.setLayout(headerPanel1Layout);
        headerPanel1Layout.setHorizontalGroup(
            headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headerPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verPaquetesTuristicos, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        headerPanel1Layout.setVerticalGroup(
            headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(verPaquetesTuristicos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1202, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6)))
                        .addGap(0, 1034, Short.MAX_VALUE))
                    .addComponent(headerPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(headerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listadoViajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoViajesMouseClicked
        // TODO add your handling code here:
        String pprecio = this.controllerPaqueteViaje.calcularPrecio(listadoViajes, listadoEstadia, listadoSeguros);
        this.lblPrecio.setText(pprecio);

        Servicio servicio = new Servicio();
        boolean activado = false;

        if (this.servicios.isEmpty()) {
            activado = true;
        }else{
            for (int i = 0; i < servicios.size(); i++) {
                servicio = servicios.get(i);

                if (servicio.getIdTipoServicio()==1 || servicio.getIdTipoServicio()==2) {
                    servicio.setIdWs(this.controllerPaqueteViaje.obtenerWS(listadoViajes));
                    activado = false;
                    break;
                } else{
                    activado = true;
                }
            }
        }
        if (activado) {
            Servicio servicioNuevo = new Servicio();
            servicioNuevo.setIdTipoServicio(2);
            if (this.transporte.getSelectedIndex()==0) {
                servicioNuevo.setIdTipoServicio(1);
            }
            servicioNuevo.setIdWs(this.controllerPaqueteViaje.obtenerWS(listadoViajes));
            this.servicios.add(servicioNuevo);
        }
    }//GEN-LAST:event_listadoViajesMouseClicked

    private void listadoEstadiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoEstadiaMouseClicked
        // TODO add your handling code here:
        String pprecio = this.controllerPaqueteViaje.calcularPrecio(listadoViajes, listadoEstadia, listadoSeguros);
        this.lblPrecio.setText(pprecio);

        Servicio servicio = new Servicio();
        boolean activado = false;

        if (this.servicios.isEmpty()) {
            activado = true;
        }else{
            for (int i = 0; i < servicios.size(); i++) {
                servicio = servicios.get(i);
                if (servicio.getIdTipoServicio()==3) {
                    servicio.setIdWs(this.controllerPaqueteViaje.obtenerWS(listadoEstadia));
                    activado = false;
                    break;
                }else{
                    activado = true;
                }
            }
        }
        if (activado) {
            Servicio servicioNuevo = new Servicio();
            servicioNuevo.setIdTipoServicio(3);
            servicioNuevo.setIdWs(this.controllerPaqueteViaje.obtenerWS(listadoEstadia));
            this.servicios.add(servicioNuevo);
        }
    }//GEN-LAST:event_listadoEstadiaMouseClicked

    private void listadoSegurosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoSegurosMouseClicked
        // TODO add your handling code here:
        String pprecio = this.controllerPaqueteViaje.calcularPrecio(listadoViajes, listadoEstadia, listadoSeguros);
        this.lblPrecio.setText(pprecio);

        Servicio servicio = new Servicio();
        boolean activado = false;

        if (this.servicios.isEmpty()) {
            activado = true;
        }else{
            for (int i = 0; i < servicios.size(); i++) {
                servicio = servicios.get(i);
                if (servicio.getIdTipoServicio()==4) {
                    servicio.setIdWs(this.controllerPaqueteViaje.obtenerWS(listadoSeguros));
                    activado = false;
                    break;
                }else{
                    activado = true;
                }
            }
        }
        if(activado){
            Servicio servicioNuevo = new Servicio();
            servicioNuevo.setIdTipoServicio(4);
            servicioNuevo.setIdWs(this.controllerPaqueteViaje.obtenerWS(listadoSeguros));
            this.servicios.add(servicioNuevo);
        }
    }//GEN-LAST:event_listadoSegurosMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        this.btnGuardar.setBackground(new Color(88,185,87));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        this.btnGuardar.setBackground(Color.black);
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int v_precio = Integer.parseInt(this.lblPrecio.getText());
        if(v_precio > 0){
            try {
                if (controllerPaqueteViaje.nuevoPaquete(descripcion.getText(),v_precio,this.servicios)) {
                    JOptionPane.showMessageDialog(this, "El paquete ha sido guardado");
                    this.limpiarTablas();
                    this.origen.setText("");
                    this.destino.setText("");
                    this.numPasajeros.setText("");
                    this.fechaRegreso.getModel().setValue(null);
                    this.fechaIda.getModel().setValue(null);
                    this.cbTipoTransporte.setSelectedIndex(0);
                    precio.setText("0");
                    this.descripcion.setText("");
                    this.activarCampos();
                } else{
                    JOptionPane.showMessageDialog(this, "ERROR");
                }
            } catch (SQLException ex) {
                Logger.getLogger(PaqueteNuevo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PaqueteNuevo.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            JOptionPane.showMessageDialog(this, "Debes completar los campos para crear un paquete.");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void verPaquetesTuristicosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verPaquetesTuristicosMouseExited
        this.verPaquetesTuristicos.setBackground(new Color(88,185,87));
    }//GEN-LAST:event_verPaquetesTuristicosMouseExited

    private void verPaquetesTuristicosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verPaquetesTuristicosMouseEntered
        this.verPaquetesTuristicos.setBackground(Color.black);
    }//GEN-LAST:event_verPaquetesTuristicosMouseEntered

    private void verPaquetesTuristicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPaquetesTuristicosActionPerformed
        // TODO add your handling code here:
        JPanel parent = HomeNewTest.getParentPanel();
        PaqueteNuevoNew listado = new PaqueteNuevoNew();
        HomeNewTest.setNewPanel(listado);
        listado.setLocation(0, 0);
        parent.removeAll();
        parent.add(listado, BorderLayout.CENTER);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_verPaquetesTuristicosActionPerformed

    private void txtDestinoPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDestinoPaisMouseClicked
        txtDestinoPais.setText("");
    }//GEN-LAST:event_txtDestinoPaisMouseClicked

    private void txtDestinoCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDestinoCiudadMouseClicked
        txtDestinoCiudad.setText("");
    }//GEN-LAST:event_txtDestinoCiudadMouseClicked

    private void txtDestinoTerminalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDestinoTerminalMouseClicked
        txtDestinoTerminal.setText("");
    }//GEN-LAST:event_txtDestinoTerminalMouseClicked

    private void txtOrigenPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOrigenPaisMouseClicked
        txtOrigenPais.setText("");
    }//GEN-LAST:event_txtOrigenPaisMouseClicked

    private void btnOtraConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtraConsultaActionPerformed
        this.activarCampos();
        this.limpiarTablas();
    }//GEN-LAST:event_btnOtraConsultaActionPerformed

    private void btnOtraConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtraConsultaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOtraConsultaMouseEntered

    private void btnOtraConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtraConsultaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOtraConsultaMouseExited

    private void btnOtraConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtraConsultaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOtraConsultaMouseClicked

    private void dateRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateRegresoActionPerformed
        try {
            if (!this.controllerPaqueteViaje.fechaValidaRegreso(fechaRegreso, fechaIda)) {
                JOptionPane.showMessageDialog(this, "No puedes seleccionar una fecha pasada");
                this.fechaRegreso.getModel().setValue(null);
            }
        } catch (ParseException ex) {
            Logger.getLogger(PaqueteNuevo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dateRegresoActionPerformed

    private void dateIdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateIdaActionPerformed
        try {
            if (!this.controllerPaqueteViaje.fechaValida(fechaIda)) {
                JOptionPane.showMessageDialog(this, "No puedes seleccionar una fecha pasada");
                this.fechaIda.getModel().setValue(null);
            }else{
                this.fechaRegreso.getModel().setValue(null);
                this.fechaRegreso.setEnabled(true);
            }
        } catch (ParseException ex) {
            Logger.getLogger(PaqueteNuevo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dateIdaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            String v_origen = origen.getText();
            int v_pasajeros = 0;
            if (!numPasajeros.getText().isEmpty()) {
                v_pasajeros = Integer.parseInt(numPasajeros.getText());
            }

            String v_destino = destino.getText();
            Date v_fecha = controllerPaqueteViaje.getCalendarFecha(fechaIda);
            int v_transporte = transporte.getSelectedIndex();

            if (v_origen.isEmpty() && v_destino.isEmpty() && v_pasajeros<=0) {
                System.out.println("campos vacios");
            } else{
                System.out.println("campos llenos");
            }

            //Viajes
            DefaultTableModel modelViajes = new DefaultTableModel();
            try {
                modelViajes = controllerPaqueteViaje.cargarViajes(v_destino, v_origen, v_origen, v_pasajeros, v_destino, v_origen, v_origen, v_fecha, v_transporte);
            } catch (IOException ex) {
                Logger.getLogger(PaqueteNuevo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(PaqueteNuevo.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.listadoViajes.setModel(modelViajes);

            //Estadia
            DefaultTableModel modelEstadia = new DefaultTableModel();
            try {
                modelEstadia = controllerPaqueteViaje.cargarEstadia(v_destino, v_pasajeros);
            } catch (IOException ex) {
                Logger.getLogger(PaqueteNuevo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(PaqueteNuevo.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.listadoEstadia.setModel(modelEstadia);

            //Seguros
            DefaultTableModel modelSeguros = new DefaultTableModel();
            try {
                modelSeguros = controllerPaqueteViaje.cargarSeguros();
            } catch (IOException ex) {
                Logger.getLogger(PaqueteNuevo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(PaqueteNuevo.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.listadoSeguros.setModel(modelSeguros);
            this.listadoEstadia.setEnabled(true);
            this.listadoSeguros.setEnabled(true);
            this.listadoViajes.setEnabled(true);
            this.dateIda.setEnabled(false);
            this.dateRegreso.setEnabled(false);
            this.btnConsultar.setEnabled(false);
            this.cbTipoTransporte.setEnabled(false);
            this.destino.setEnabled(false);
            this.numPasajeros.setEnabled(false);
            this.origen.setEnabled(false);
            this.btnOtraConsulta.setEnabled(true);
        } catch (ParseException ex) {
            Logger.getLogger(PaqueteNuevo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseEntered
        // TODO add your handling code here:
        btnConsultar.setBackground(Color.black);
    }//GEN-LAST:event_btnConsultarMouseEntered

    private void btnConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseExited
        // TODO add your handling code here:
        btnConsultar.setBackground(new Color(88,185,87));
    }//GEN-LAST:event_btnConsultarMouseExited

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked

    }//GEN-LAST:event_btnConsultarMouseClicked

    private void txtNumPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPasajerosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNumPasajerosActionPerformed

    private void txtOrigenCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOrigenCiudadMouseClicked
        txtOrigenCiudad.setText("");
    }//GEN-LAST:event_txtOrigenCiudadMouseClicked

    private void txtOrigenTerminalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOrigenTerminalMouseClicked
        txtOrigenTerminal.setText("");
    }//GEN-LAST:event_txtOrigenTerminalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnOtraConsulta;
    private javax.swing.JComboBox<String> cbTipoTransporte;
    private org.jdatepicker.JDatePanel dateIda;
    private org.jdatepicker.JDatePanel dateRegreso;
    private javax.swing.JPanel headerPanel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTable listadoEstadia;
    private javax.swing.JTable listadoSeguros;
    private javax.swing.JTable listadoViajes;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDestinoCiudad;
    private javax.swing.JTextField txtDestinoPais;
    private javax.swing.JTextField txtDestinoTerminal;
    private javax.swing.JTextField txtNumPasajeros;
    private javax.swing.JTextField txtOrigenCiudad;
    private javax.swing.JTextField txtOrigenPais;
    private javax.swing.JTextField txtOrigenTerminal;
    private javax.swing.JButton verPaquetesTuristicos;
    // End of variables declaration//GEN-END:variables
}
