/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConPaqueteViaje;
import dto.Servicio;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jdatepicker.JDatePanel;

/**
 *
 * @author luisponce
 */
public class PaqueteListado extends javax.swing.JPanel {
    /**
     * Creates new form UsuarioNuevo
     */
    private JTextField origen, numPasajeros, destino;
    private JDatePanel fechaIda, fechaRegreso;
    private JComboBox transporte;
    private int idPaqueteTuristico = 0;
    
    ConPaqueteViaje controllerPaqueteViaje = new ConPaqueteViaje();
    /**
     * Creates new form PaqueteListadoNew
     */
    public PaqueteListado() {
        initComponents();
        this.actualizar();
    }
    
    public void limpiarTablas(){
        DefaultTableModel model = (DefaultTableModel) this.listadoTransporte.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model = (DefaultTableModel) this.listadoEstadia.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model = (DefaultTableModel) this.listadoSeguros.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
    }
    
    public void actualizar(){
        DefaultTableModel modelViajes = new DefaultTableModel();
        try {
            modelViajes = controllerPaqueteViaje.listarPaquetes();
        } catch (SQLException ex) {
            Logger.getLogger(PaqueteListado.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.listadoPaquetes.setModel(modelViajes);
        this.listadoPaquetes.getColumnModel().getColumn(0).setPreferredWidth(60);
        this.listadoPaquetes.getColumnModel().getColumn(1).setPreferredWidth(560);
        this.listadoPaquetes.getColumnModel().getColumn(2).setPreferredWidth(100);
        this.btnBorrar.setEnabled(false);
        this.limpiarTablas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoPaquetes = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listadoTransporte = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listadoEstadia = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listadoSeguros = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        crearPaqueteTuristico = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(245, 245, 245));

        listadoPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listadoPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoPaquetesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listadoPaquetes);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel9.setBackground(new java.awt.Color(245, 245, 245));

        listadoTransporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listadoTransporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoTransporteMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(listadoTransporte);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Transporte");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Estadia");

        listadoEstadia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listadoEstadia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoEstadiaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listadoEstadia);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Seguros");

        listadoSeguros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listadoSeguros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoSegurosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(listadoSeguros);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(38, 38, 38)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(245, 245, 245));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Servicios vinculados al paquete seleccionado:");

        btnBorrar.setBackground(new java.awt.Color(88, 185, 87));
        btnBorrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnBorrar.setForeground(java.awt.Color.white);
        btnBorrar.setText("Eliminar paquete turístico");
        btnBorrar.setBorderPainted(false);
        btnBorrar.setContentAreaFilled(false);
        btnBorrar.setFocusPainted(false);
        btnBorrar.setIgnoreRepaint(true);
        btnBorrar.setOpaque(true);
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBorrarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBorrarMouseEntered(evt);
            }
        });
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrar)
                .addGap(35, 35, 35))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("Paquetes");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("|   Listado");

        jLabel19.setFont(new java.awt.Font("Open Sans", 2, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Haz clic sobre un paquete para ver sus servicios");

        crearPaqueteTuristico.setBackground(new java.awt.Color(88, 185, 87));
        crearPaqueteTuristico.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        crearPaqueteTuristico.setForeground(java.awt.Color.white);
        crearPaqueteTuristico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-add.png"))); // NOI18N
        crearPaqueteTuristico.setText("Crear paquete turístico");
        crearPaqueteTuristico.setBorderPainted(false);
        crearPaqueteTuristico.setContentAreaFilled(false);
        crearPaqueteTuristico.setFocusPainted(false);
        crearPaqueteTuristico.setOpaque(true);
        crearPaqueteTuristico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearPaqueteTuristicoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearPaqueteTuristicoMouseEntered(evt);
            }
        });
        crearPaqueteTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPaqueteTuristicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crearPaqueteTuristico, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(crearPaqueteTuristico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listadoPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoPaquetesMouseClicked
        int paqueteSeleccionado = this.listadoPaquetes.getSelectedRow();
        BigDecimal numeroPaquete = (BigDecimal) this.listadoPaquetes.getModel().getValueAt(paqueteSeleccionado, 0);
        idPaqueteTuristico = numeroPaquete.intValue();
        DefaultTableModel model = (DefaultTableModel) this.listadoTransporte.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model = (DefaultTableModel) this.listadoEstadia.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model = (DefaultTableModel) this.listadoSeguros.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        this.btnBorrar.setEnabled(true);
        try {
            List<Servicio> servicios = this.controllerPaqueteViaje.getServiciosElegidos(numeroPaquete);
            for (Servicio servicio : servicios) {
                int idWs = servicio.getIdWs();
                switch(servicio.getIdTipoServicio()){
                    case 1:
                    //vuelo
                    try {
                        DefaultTableModel modelVuelo = new DefaultTableModel();
                        modelVuelo = this.controllerPaqueteViaje.getVueloConId(idWs);
                        this.listadoTransporte.setModel(modelVuelo);
                    } catch (IOException ex) {
                        Logger.getLogger(PaqueteListado.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                    case 2:
                    //Bus
                    try {
                        DefaultTableModel modelBus = new DefaultTableModel();
                        modelBus = this.controllerPaqueteViaje.getBusConId(idWs);
                        this.listadoTransporte.setModel(modelBus);
                    } catch (IOException ex) {
                        Logger.getLogger(PaqueteListado.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                    case 3:
                    //Estadia
                    try {
                        DefaultTableModel modelEstadia = new DefaultTableModel();
                        modelEstadia = this.controllerPaqueteViaje.getEstadiaConId(idWs);
                        this.listadoEstadia.setModel(modelEstadia);
                    } catch (IOException ex) {
                        Logger.getLogger(PaqueteListado.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                    case 4:
                    //Seguro
                    try {
                        DefaultTableModel modelSeguro = new DefaultTableModel();
                        modelSeguro = this.controllerPaqueteViaje.getSeguroConId(idWs);
                        this.listadoSeguros.setModel(modelSeguro);
                    } catch (IOException ex) {
                        Logger.getLogger(PaqueteListado.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                    case 5:
                    //actividad
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PaqueteListado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PaqueteListado.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_listadoPaquetesMouseClicked

    private void listadoTransporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoTransporteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoTransporteMouseClicked

    private void listadoEstadiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoEstadiaMouseClicked

    }//GEN-LAST:event_listadoEstadiaMouseClicked

    private void listadoSegurosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoSegurosMouseClicked

    }//GEN-LAST:event_listadoSegurosMouseClicked

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarMouseClicked

    private void btnBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseExited
        this.btnBorrar.setBackground(new Color(88,185,87));
    }//GEN-LAST:event_btnBorrarMouseExited

    private void btnBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseEntered
        this.btnBorrar.setBackground(Color.black);
    }//GEN-LAST:event_btnBorrarMouseEntered

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int row = this.listadoPaquetes.getSelectedRow();
        try {
            if (this.controllerPaqueteViaje.eliminarPaqueteViaje(this.idPaqueteTuristico)) {
                JOptionPane.showMessageDialog(this, "El paquete turístico ha sido eliminado");

                DefaultTableModel usuarioTableModel = (DefaultTableModel) this.listadoPaquetes.getModel();
                usuarioTableModel.removeRow(row);
                this.listadoPaquetes.revalidate();
                this.limpiarTablas();
                this.btnBorrar.setEnabled(false);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PaqueteListado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PaqueteListado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void crearPaqueteTuristicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearPaqueteTuristicoMouseExited
        this.crearPaqueteTuristico.setBackground(new Color(88,185,87));
    }//GEN-LAST:event_crearPaqueteTuristicoMouseExited

    private void crearPaqueteTuristicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearPaqueteTuristicoMouseEntered
        this.crearPaqueteTuristico.setBackground(Color.black);
    }//GEN-LAST:event_crearPaqueteTuristicoMouseEntered

    private void crearPaqueteTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPaqueteTuristicoActionPerformed
        // TODO add your handling code here:
        JPanel parent = Home.getParentPanel();
        PaqueteNuevo listado = new PaqueteNuevo();
        Home.setNewPanel(listado);
        listado.setLocation(0, 0);
        parent.removeAll();
        parent.add(listado, BorderLayout.CENTER);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_crearPaqueteTuristicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton crearPaqueteTuristico;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable listadoEstadia;
    private javax.swing.JTable listadoPaquetes;
    private javax.swing.JTable listadoSeguros;
    private javax.swing.JTable listadoTransporte;
    // End of variables declaration//GEN-END:variables
}
